shopware:
  filesystem:
    private:
      type: "local"
      config:
        root: "%kernel.project_dir%/files"
    public:
      url: "https://%env(AWS_BUCKET)%.s3.%env(AWS_REGION)%.%env(AWS_DOMAIN)%" #https://bucketName.s3.regionName.amazonaws.com
      type: "amazon-s3"
      visibility: "public"
      config:
        bucket: "%env(AWS_BUCKET)%"
        region: "%env(AWS_REGION)%"
        root: "%env(AWS_ROOT)%"
        endpoint: "https://s3.%env(AWS_REGION)%.%env(AWS_DOMAIN)%" #https://s3.ap-southeast-1.amazonaws.com
        credentials:
          key: "%env(AWS_CREDENTIAL_KEY)%"
          secret: "%env(AWS_CREDENTIAL_SECRET)%"
    theme:
      url: ""
      type: "local"
      config:
        root: "%kernel.project_dir%/public"
    temp:
      type: "local"
      config:
        root: "%kernel.project_dir%/var"
    asset:
      url: ""
      type: "local"
      config:
        root: "%kernel.project_dir%/public"
    sitemap:
      url: ""
      type: "local"
      config:
        root: "%kernel.project_dir%/public"
