version: "3"

services:
  shopware:
    image: dockware/dev:6.4.11.1
    container_name: shopware
    ports:
      - "80:80"
      - "4306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
    volumes:
      - ./:/var/www/html
      - db_volume:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:7.17.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    networks:
      - web
    environment:
      - "EA_JAVA_OPTS=-Xms512m -Xms512m"
      - discovery.type=single-node
    volumes:
      - es_volume:/usr/share/elasticsearch/data

  redis:
    image: redis
    container_name: redis
    networks:
      - web

volumes:
  db_volume:
    driver: local
  es_volume:
    driver: local

networks:
  web:
    external: false