version: "3"

services:
  shopware:
    image: dockware/essentials:latest
    container_name: shopware
    ports:
      - "8000:80"
      - "4306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
    volumes:
      - ./:/var/www/html
      - db_volume:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:7.17.4
    container_name: elasticsearch
    networks:
      - web
    environment:
      - "EA_JAVA_OPTS=-Xms512m -Xms512m"
      - discovery.type=single-node

  redis:
    image: redis
    container_name: redis
    networks:
      - web

volumes:
  db_volume:
    driver: local

networks:
  web:
    external: false